// @ts-check
import { SITE } from './site';

/**
 * @typedef {Object} RouteEntry
 * @property {string} path
 * @property {string} title
 * @property {string} description
 * @property {string} h1
 * @property {string} primaryKeyword
 * @property {string} breadcrumbLabel
 * @property {string} [parent]
 * @property {"web"|"branding"|"video"|"social"|"ai"|"seo"} [category]
 * @property {boolean} inSitemap
 * @property {string[]} schema
 * @property {number} [fromPriceGBP]
 * @property {number} [setupFeeGBP]
 * @property {"one-off"|"monthly"} [billing]
 * @property {string} updatedAt
 */

/**
 * Build Next.js metadata from route data.
 * Every indexable page must call this — no page may fall back to the root title.
 * @param {{ path: string, title: string, description: string, image?: string, noindex?: boolean }} opts
 * @returns {import('next').Metadata}
 */
export function buildMetadata({ path, title, description, image, noindex = false }) {
  const url = `${SITE.url}${path}`;
  const ogImage = image || `${SITE.url}/images/og-default.jpg`;
  return {
    title: { absolute: title },
    description,
    alternates: { canonical: url },
    openGraph: {
      url,
      title,
      description,
      siteName: SITE.name,
      locale: 'en_GB',
      type: 'website',
      images: [{ url: ogImage, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
    robots: noindex
      ? { index: false, follow: false }
      : { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  };
}

/** @type {RouteEntry[]} */
export const ROUTES = [
  {
    path: '/',
    title: 'Maxterz | Web Design, Branding and AI Agency',
    description: 'UK-registered digital agency for websites, branding, video, SEO and AI agents. 10,000+ projects delivered since 2017. Book a free strategy call.',
    h1: 'Your Entire Digital Team Under One Roof.',
    primaryKeyword: 'digital agency, web design and branding agency',
    breadcrumbLabel: 'Home',
    inSitemap: true,
    schema: ['WebPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services',
    title: 'Services: Websites, Branding, Video, SEO and AI | Maxterz',
    description: 'One team for websites, apps, branding, video, social media, SEO and AI automation. Clear prices, fixed timelines and one point of contact.',
    h1: 'Digital Agency Services for Growing Businesses',
    primaryKeyword: 'digital agency services',
    breadcrumbLabel: 'Services',
    inSitemap: true,
    schema: ['WebPage', 'ItemList'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/web-development',
    title: 'Web Design and App Development Agency | Maxterz',
    description: 'Fast, SEO-ready websites, ecommerce stores and mobile apps built to win enquiries. Fixed prices, clear timelines and full code handover.',
    h1: 'Web Design and App Development That Wins You Clients',
    primaryKeyword: 'web design and development agency',
    breadcrumbLabel: 'Web and App Development',
    parent: '/services',
    category: 'web',
    inSitemap: true,
    schema: ['WebPage', 'Service'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/web-development/business-website-design',
    title: 'Business Website Design That Wins Enquiries | Maxterz',
    description: 'Business websites built to turn visitors into calls and bookings. Mobile-first, fast and SEO-ready, with a launch date agreed before we start.',
    h1: 'Business Website Design That Wins Enquiries',
    primaryKeyword: 'business website design',
    breadcrumbLabel: 'Business Website Design',
    parent: '/services/web-development',
    category: 'web',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/web-development/ecommerce-website-design',
    title: 'Ecommerce Website Design and Development | Maxterz',
    description: 'Online stores built for fast checkout and repeat sales. Shopify or custom builds with SEO, tracking and payments set up from day one.',
    h1: 'Ecommerce Website Design Built to Sell',
    primaryKeyword: 'ecommerce website design',
    breadcrumbLabel: 'Ecommerce Website Design',
    parent: '/services/web-development',
    category: 'web',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/web-development/app-design',
    title: 'App Design and UI/UX Design Services | Maxterz',
    description: 'App and product design that users understand at first tap. Research, wireframes, clickable prototypes and developer-ready design files.',
    h1: 'App Design and UI/UX That Users Understand',
    primaryKeyword: 'app design, UI/UX design services',
    breadcrumbLabel: 'App Design',
    parent: '/services/web-development',
    category: 'web',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/web-development/mobile-app-development',
    title: 'Mobile App Development for iOS and Android | Maxterz',
    description: 'Cross-platform mobile apps built around your customers and workflows. From first prototype to app store launch, with one team throughout.',
    h1: 'Mobile App Development for iOS and Android',
    primaryKeyword: 'mobile app development',
    breadcrumbLabel: 'Mobile App Development',
    parent: '/services/web-development',
    category: 'web',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/branding-design',
    title: 'Logo Design and Branding Agency | Maxterz',
    description: 'Logos, brand identities and social media design that make your business look established. From the team behind 10,000+ projects since 2017.',
    h1: 'Logo Design and Branding That Makes You Look Established',
    primaryKeyword: 'logo design and branding agency',
    breadcrumbLabel: 'Branding and Design',
    parent: '/services',
    category: 'branding',
    inSitemap: true,
    schema: ['WebPage', 'Service'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/branding-design/logo-design',
    title: 'Logo Design Services for Growing Businesses | Maxterz',
    description: 'Original logo design with multiple concepts, clear revision rounds and every file format you need. Add a logo animation to launch with impact.',
    h1: 'Logo Design Services for Growing Businesses',
    primaryKeyword: 'logo design services',
    breadcrumbLabel: 'Logo Design',
    parent: '/services/branding-design',
    category: 'branding',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/branding-design/brand-identity-design',
    title: 'Brand Identity Design and Brand Guidelines | Maxterz',
    description: 'Complete brand identity systems: logo suite, colours, typography, templates and guidelines that keep every touchpoint consistent.',
    h1: 'Brand Identity Design and Guidelines',
    primaryKeyword: 'brand identity design',
    breadcrumbLabel: 'Brand Identity Design',
    parent: '/services/branding-design',
    category: 'branding',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/branding-design/social-media-design',
    title: 'Social Media Design: Posts, Carousels and Ads | Maxterz',
    description: 'On-brand social media graphics, carousels, story templates and ad creatives designed to stop the scroll and match your brand.',
    h1: 'Social Media Design That Stops the Scroll',
    primaryKeyword: 'social media design services',
    breadcrumbLabel: 'Social Media Design',
    parent: '/services/branding-design',
    category: 'branding',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/branding-design/thumbnail-design',
    title: 'YouTube Thumbnail Design by ThumbLab | Maxterz',
    description: 'Click-worthy YouTube thumbnails from ThumbLab, the thumbnail studio by Maxterz. Designed to earn the click on every upload you publish.',
    h1: 'YouTube Thumbnail Design by ThumbLab',
    primaryKeyword: 'YouTube thumbnail design',
    breadcrumbLabel: 'Thumbnail Design',
    parent: '/services/branding-design',
    category: 'branding',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/video-animation',
    title: 'Video, Motion Graphics and Animation Agency | Maxterz',
    description: 'Logo animations, motion graphics, explainer videos and short-form edits from the studio behind a logo animation with 1.2M views.',
    h1: 'Video, Motion Graphics and Animation',
    primaryKeyword: 'motion graphics and animation agency',
    breadcrumbLabel: 'Video and Animation',
    parent: '/services',
    category: 'video',
    inSitemap: true,
    schema: ['WebPage', 'Service'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/video-animation/logo-animation',
    title: 'Logo Animation Services: Intros and Reveals | Maxterz',
    description: 'Custom logo animations for intros, outros, websites and social media. Made by the studio with 1,000+ logo animation reviews on Fiverr and a 1.2M-view reel.',
    h1: 'Logo Animation Services',
    primaryKeyword: 'logo animation services',
    breadcrumbLabel: 'Logo Animation',
    parent: '/services/video-animation',
    category: 'video',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/video-animation/motion-graphics',
    title: 'Motion Graphics Design Services | Maxterz',
    description: 'Motion graphics for ads, product launches, social media and presentations. Clear storyboards, fast delivery and files for every platform.',
    h1: 'Motion Graphics Design Services',
    primaryKeyword: 'motion graphics services',
    breadcrumbLabel: 'Motion Graphics',
    parent: '/services/video-animation',
    category: 'video',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/video-animation/video-editing',
    title: 'Video Editing for Reels, Shorts and YouTube | Maxterz',
    description: 'Edits for reels, TikTok and Shorts, talking-head videos and YouTube, with captions, music and motion text. Try one edit, buy a pack or go monthly.',
    h1: 'Video Editing for Reels, Shorts and YouTube',
    primaryKeyword: 'video editing services, reels editing',
    breadcrumbLabel: 'Video Editing',
    parent: '/services/video-animation',
    category: 'video',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/video-animation/explainer-videos',
    title: 'Explainer Video Production and SaaS Demos | Maxterz',
    description: 'Script-to-screen explainer and product demo videos that make complex offers simple. Script, voiceover, animation and edit in one place.',
    h1: 'Explainer Video Production',
    primaryKeyword: 'explainer video production',
    breadcrumbLabel: 'Explainer Videos',
    parent: '/services/video-animation',
    category: 'video',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/social-media-management',
    title: 'Social Media Management Agency | Maxterz',
    description: 'Done-for-you social media: strategy, content, posting and community management that turns followers into enquiries. Simple monthly plans.',
    h1: 'Social Media Management That Brings Enquiries',
    primaryKeyword: 'social media management agency',
    breadcrumbLabel: 'Social Media Management',
    parent: '/services',
    category: 'social',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/ai-automation',
    title: 'AI Automation Agency: AI Agents and Workflows | Maxterz',
    description: 'AI receptionists, WhatsApp and chat agents, and workflow automation that answer customers 24/7 and take repetitive admin off your team.',
    h1: 'AI Agents and Automation for Your Business',
    primaryKeyword: 'AI automation agency',
    breadcrumbLabel: 'AI and Automation',
    parent: '/services',
    category: 'ai',
    inSitemap: true,
    schema: ['WebPage', 'Service'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/ai-automation/ai-receptionist',
    title: 'AI Receptionist for Small Businesses | Maxterz',
    description: 'An AI receptionist that answers every call 24/7, books appointments, qualifies leads and sends you a summary. Tested before it takes a real call.',
    h1: 'An AI Receptionist That Answers Every Call',
    primaryKeyword: 'AI receptionist',
    breadcrumbLabel: 'AI Receptionist',
    parent: '/services/ai-automation',
    category: 'ai',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/ai-automation/ai-chat-agents',
    title: 'AI Chat Agents for WhatsApp, SMS and Websites | Maxterz',
    description: 'AI text agents that reply in seconds on WhatsApp, SMS and your website. They answer questions, capture leads and book calls around the clock.',
    h1: 'AI Chat Agents for WhatsApp, SMS and Your Website',
    primaryKeyword: 'AI chatbot for business, WhatsApp AI agent',
    breadcrumbLabel: 'AI Chat Agents',
    parent: '/services/ai-automation',
    category: 'ai',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/seo-digital-marketing',
    title: 'SEO and Digital Marketing Agency | Maxterz',
    description: 'Technical SEO, local SEO, content and paid ads that bring qualified traffic and measurable enquiries. Clear monthly reports you can read.',
    h1: 'SEO and Digital Marketing That Brings Enquiries',
    primaryKeyword: 'SEO agency',
    breadcrumbLabel: 'SEO and Digital Marketing',
    parent: '/services',
    category: 'seo',
    inSitemap: true,
    schema: ['WebPage', 'Service'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/seo-digital-marketing/seo-services',
    title: 'SEO Services That Bring Qualified Traffic | Maxterz',
    description: 'Technical SEO, on-page optimisation, content and link building that grow qualified organic traffic, with clear monthly reports you can read.',
    h1: 'SEO Services That Bring Qualified Traffic',
    primaryKeyword: 'SEO services',
    breadcrumbLabel: 'SEO Services',
    parent: '/services/seo-digital-marketing',
    category: 'seo',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/services/seo-digital-marketing/local-seo',
    title: 'Local SEO Services and Google Business Profile | Maxterz',
    description: 'Get found in Google Maps and local results. Google Business Profile optimisation, local pages, citations and reviews that bring in local calls.',
    h1: 'Local SEO Services That Bring Local Calls',
    primaryKeyword: 'local SEO services',
    breadcrumbLabel: 'Local SEO',
    parent: '/services/seo-digital-marketing',
    category: 'seo',
    inSitemap: true,
    schema: ['WebPage', 'Service', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/packages',
    title: 'Packages and Pricing: Websites, Branding and AI | Maxterz',
    description: 'Clear starting prices for websites, branding, animation, SEO, social media and AI agents. Fixed-price projects and simple monthly plans.',
    h1: 'Packages and Pricing',
    primaryKeyword: 'website packages and prices',
    breadcrumbLabel: 'Packages and Pricing',
    inSitemap: true,
    schema: ['WebPage', 'OfferCatalog'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/packages/launch-kit',
    title: 'Launch Kit: Brand, Website and Google Set-up | Maxterz',
    description: 'Everything a small business needs to look established and get found: brand identity, website, Google profile and social set-up, live in 21 working days.',
    h1: 'Launch Kit: Brand, Website and Google, Done for You',
    primaryKeyword: 'website and branding package for small businesses',
    breadcrumbLabel: 'Launch Kit',
    parent: '/packages',
    inSitemap: true,
    schema: ['WebPage', 'FAQPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/our-work',
    title: 'Our Work: Websites, Branding and Animation | Maxterz',
    description: 'Case studies and selected projects across websites, apps, branding, logo animation and AI. See what we built and how it works for each client.',
    h1: 'Our Work',
    primaryKeyword: 'agency portfolio',
    breadcrumbLabel: 'Our Work',
    inSitemap: true,
    schema: ['CollectionPage', 'ItemList'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/about',
    title: 'About Maxterz: The Team Behind 10,000+ Projects',
    description: 'Maxterz is a UK-registered digital agency with 10,000+ projects delivered since 2017, led by a founder with an MSc in Software Engineering.',
    h1: 'About Maxterz',
    primaryKeyword: 'about Maxterz',
    breadcrumbLabel: 'About',
    inSitemap: true,
    schema: ['AboutPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/reviews',
    title: 'Client Reviews: 4.9 Stars on Fiverr | Maxterz',
    description: 'Read what clients say about Maxterz: 4.9 stars from 7,000+ reviews on Fiverr since 2017. Filter by service to see feedback on work like yours.',
    h1: 'Client Reviews',
    primaryKeyword: 'Maxterz reviews',
    breadcrumbLabel: 'Reviews',
    inSitemap: true,
    schema: ['WebPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/contact',
    title: 'Contact Maxterz: Get a Quote or Book a Call',
    description: 'Tell us about your project and get a clear plan and quote within one working day. Call, WhatsApp, email or book a free strategy call.',
    h1: 'Contact Maxterz',
    primaryKeyword: 'contact Maxterz',
    breadcrumbLabel: 'Contact',
    inSitemap: true,
    schema: ['ContactPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/book',
    title: 'Book a Free 30-Minute Strategy Call | Maxterz',
    description: 'Pick a time that suits you. In 30 minutes we map your goals, spot quick wins and recommend the right next step. No obligation.',
    h1: 'Book a Free Strategy Call',
    primaryKeyword: 'book a call',
    breadcrumbLabel: 'Book a Call',
    inSitemap: true,
    schema: ['WebPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/free-website-audit',
    title: 'Free Website Audit Video in 48 Hours | Maxterz',
    description: 'Get a personal video audit of your website covering speed, SEO and conversion, plus the three fixes that would bring you more enquiries.',
    h1: 'Get a Free Website Audit Video',
    primaryKeyword: 'free website audit',
    breadcrumbLabel: 'Free Website Audit',
    inSitemap: true,
    schema: ['WebPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/insights',
    title: 'Insights: Guides on Web, Branding, SEO and AI | Maxterz',
    description: 'Practical guides on websites, branding, SEO and AI automation for business owners. Costs, checklists and lessons from real projects.',
    h1: 'Insights',
    primaryKeyword: 'digital agency insights',
    breadcrumbLabel: 'Insights',
    inSitemap: true,
    schema: ['CollectionPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/privacy-policy',
    title: 'Privacy Policy: How We Handle Your Data | Maxterz',
    description: 'How MAXTERZ LTD collects, uses and protects personal data from our website, forms and bookings, and how to use your rights under UK GDPR.',
    h1: 'Privacy Policy',
    primaryKeyword: 'privacy policy',
    breadcrumbLabel: 'Privacy Policy',
    inSitemap: true,
    schema: ['WebPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/terms-conditions',
    title: 'Terms and Conditions for Our Website and Services | Maxterz',
    description: 'The terms that apply when you use the Maxterz website or buy our services, including quotes, payments, revisions, ownership and governing law.',
    h1: 'Terms and Conditions',
    primaryKeyword: 'terms and conditions',
    breadcrumbLabel: 'Terms and Conditions',
    inSitemap: true,
    schema: ['WebPage'],
    updatedAt: '2026-10-02',
  },
  {
    path: '/cookie-policy',
    title: 'Cookie Policy: Cookies We Use and Why | Maxterz',
    description: 'Every cookie and storage item used on the Maxterz website, what it does, how long it lasts and how to change your cookie settings at any time.',
    h1: 'Cookie Policy',
    primaryKeyword: 'cookie policy',
    breadcrumbLabel: 'Cookie Policy',
    inSitemap: true,
    schema: ['WebPage'],
    updatedAt: '2026-10-02',
  },
];
