import React, { useState, useEffect } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  ArrowRight, ArrowUpRight, Loader2, CheckCircle, Star, ShieldCheck,
  Calendar, TrendingUp, Search, Target, Globe, BarChart2, Tag,
  Link2, FileSearch, PenLine, Lightbulb, ChevronRight,
} from 'lucide-react';
import { supabase } from '@/lib/customSupabaseClient';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import CTASection from '@/components/home/CTASection';

/* ─── keyframes ───────────────────────────────────────────────── */
const SEO_STYLES = `
  @keyframes seo-blink   { 0%,100%{opacity:1} 50%{opacity:0} }
  @keyframes seo-float   { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-7px)} }
  @keyframes seo-pulse   { 0%,100%{opacity:.6;transform:scale(1)} 50%{opacity:1;transform:scale(1.12)} }
  @keyframes seo-ping    { 0%{transform:scale(1);opacity:.7} 75%,100%{transform:scale(2.4);opacity:0} }
  @keyframes seo-marquee { from{transform:translateX(0)} to{transform:translateX(-50%)} }
  @keyframes seo-rise    { 0%,100%{transform:scaleY(.38)} 50%{transform:scaleY(1)} }
  @keyframes seo-rise2   { 0%,100%{transform:scaleY(.55)} 50%{transform:scaleY(1)} }
  @keyframes seo-rise3   { 0%,100%{transform:scaleY(.28)} 50%{transform:scaleY(.78)} }
  @keyframes seo-node    { 0%,100%{opacity:.28} 50%{opacity:.90} }
  @keyframes seo-bar     { 0%,100%{transform:scaleY(.42)} 50%{transform:scaleY(1)} }
`;

/* ─── typewriter ──────────────────────────────────────────────── */
const PHRASES = ['Get Revenue.', 'Get Leads.', 'Get Rankings.', 'Get Ahead.'];

const TypeWriter = () => {
  const [displayed,  setDisplayed]  = useState('');
  const [phraseIdx,  setPhraseIdx]  = useState(0);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const phrase = PHRASES[phraseIdx];
    let delay;
    if (!isDeleting && displayed === phrase)    delay = setTimeout(() => setIsDeleting(true), 2200);
    else if (isDeleting && displayed === '')    delay = setTimeout(() => { setIsDeleting(false); setPhraseIdx(i => (i + 1) % PHRASES.length); }, 400);
    else if (isDeleting)                        delay = setTimeout(() => setDisplayed(phrase.slice(0, displayed.length - 1)), 44);
    else                                        delay = setTimeout(() => setDisplayed(phrase.slice(0, displayed.length + 1)), 86);
    return () => clearTimeout(delay);
  }, [displayed, phraseIdx, isDeleting]);

  return (
    <span>
      {displayed}
      <span className="inline-block w-[3px] h-[0.82em] bg-[#1044ff] ml-[3px] align-middle" style={{ animation: 'seo-blink 1s ease-in-out infinite' }} />
    </span>
  );
};

/* ─── static data ─────────────────────────────────────────────── */
const marqueeWords = [
  'ON-PAGE SEO', 'OFF-PAGE SEO', 'GOOGLE ADS', 'META ADS', 'TECHNICAL AUDIT',
  'KEYWORD RESEARCH', 'LINK BUILDING', 'LOCAL SEO', 'SERP RANKINGS',
  'CORE WEB VITALS', 'CONTENT STRATEGY', 'SCHEMA MARKUP', 'ORGANIC TRAFFIC',
];

const statsData = [
  { value: '93%', label: 'of all online experiences begin with a search engine. If you are not on page one, you are invisible to your market.' },
  { value: '#1',  label: 'the top organic result gets 28.5% of all clicks. Position five drops to 6.3%. Most businesses sit on page two and wonder why.' },
  { value: '14×', label: 'more leads generated by inbound SEO compared to outbound marketing on average — at a fraction of the long-term cost.' },
];

const services = [
  {
    id: 'seo', badge: 'ON-PAGE / OFF-PAGE', animType: 'seo',
    title: 'SEO Services',
    desc: 'Full-spectrum search engine optimisation. On-page covers every title, heading, content block, and internal link. Off-page covers the authority signals, backlinks, and digital PR that tell Google your site deserves to rank above everyone else.',
    tags: ['On-Page Optimisation', 'Link Building', 'Content SEO', 'Local SEO'],
    large: true,
  },
  {
    id: 'paid', badge: 'PPC', animType: 'paid',
    title: 'Paid Advertising',
    desc: 'Google Ads, Meta Ads, and paid search campaigns that put you in front of people actively searching for what you sell. Every campaign is built, managed, and optimised for cost-per-lead — not vanity metrics.',
    tags: ['Google Ads', 'Meta Ads', 'PPC Management', 'Retargeting'],
    large: true,
  },
  {
    id: 'technical', badge: 'TECHNICAL', animType: 'technical',
    title: 'Technical SEO and Audits',
    desc: 'Site speed, crawlability, Core Web Vitals, schema markup, indexation issues — the infrastructure layer that separates sites Google loves from sites it ignores. We audit, fix, and monitor.',
    tags: ['Core Web Vitals', 'Schema Markup', 'Site Speed', 'Crawl Audit'],
    large: false,
  },
  {
    id: 'keyword', badge: 'RESEARCH', animType: 'keyword',
    title: 'Keyword Research',
    desc: 'Finding the exact terms your ideal customers type into Google and mapping them to pages that can rank. No guesswork, no vanity keywords — just commercial intent keywords that drive qualified traffic.',
    tags: ['Search Intent', 'Competitor Gap', 'Long-Tail Strategy', 'Content Map'],
    large: false,
  },
];

const processSteps = [
  { n: '01', icon: <FileSearch className="w-5 h-5" />,  title: 'SEO Audit and Baseline',       desc: 'A full technical and content audit of your existing site. We find what is blocking your rankings, benchmark where you are today, and identify your biggest opportunities before writing a single line of strategy.' },
  { n: '02', icon: <Lightbulb className="w-5 h-5" />,   title: 'Keyword and Content Strategy',  desc: 'Deep research into what your target audience is actually searching for. We build a keyword map and content strategy that matches your business goals to the exact search terms that will drive qualified traffic.' },
  { n: '03', icon: <PenLine className="w-5 h-5" />,     title: 'On-Page Optimisation',          desc: 'Every page title, meta description, heading hierarchy, internal link, image alt text, and content block optimised. Both for search engines to understand and for visitors to convert when they arrive.' },
  { n: '04', icon: <Globe className="w-5 h-5" />,       title: 'Off-Page and Technical',        desc: 'Link building, digital PR, Core Web Vitals, schema implementation, and crawl health. The trust signals and technical infrastructure that determines where Google places you relative to your competitors.' },
  { n: '05', icon: <TrendingUp className="w-5 h-5" />,  title: 'Track, Report and Compound',    desc: 'Monthly reports covering keyword rankings, organic traffic, and leads attributed to search. Each month\'s data informs the next month\'s work. SEO compounds — it gets stronger the longer you invest.' },
];

const faqData = [
  { q: 'How long does SEO take to show results?',
    a: 'Honest answer: three to six months for meaningful movement on competitive terms, with compounding growth from there. Some quick-win optimisations can improve rankings within weeks. We set a clear baseline in month one so you can see progress objectively throughout. SEO is an investment in long-term organic revenue, not a quick-fix channel.' },
  { q: 'Do you guarantee first-page rankings?',
    a: 'No agency can honestly guarantee specific positions — Google\'s algorithm has over 200 ranking factors and changes constantly. What we guarantee is the work: a proven process, transparent monthly reporting, and strategies aligned with how Google actually rewards sites in 2025 and beyond. Our track record speaks to what consistent, quality SEO produces.' },
  { q: 'What is the difference between on-page and off-page SEO?',
    a: 'On-page covers everything within your website — content, titles, headings, internal links, page speed, schema. Off-page covers signals from outside your site — backlinks, digital PR, brand mentions, and authority signals. You need both to rank competitively. Optimising only one is like training only your left arm.' },
  { q: 'Do you work on paid ads and organic SEO together?',
    a: 'Yes, and the combination is often more powerful than either alone. Paid ads give you immediate visibility while organic SEO builds long-term compounding traffic. We use data from paid campaigns to inform keyword strategy and vice versa. Clients who run both channels with us typically see better ROI across both.' },
  { q: 'How do you measure success?',
    a: 'Rankings, organic traffic, and leads generated from search — in that order. We track every target keyword weekly, report organic sessions monthly, and work with you to attribute leads back to search where possible. Vanity metrics like domain authority are reported but never the headline. Revenue-relevant numbers always come first.' },
];

/* ─── animated icons ──────────────────────────────────────────── */
const cellAnimMap = {
  seo: (
    <svg viewBox="0 0 80 80" fill="none">
      <circle cx="33" cy="33" r="23" stroke="#1044ff" strokeWidth="2.5" opacity="0.18" />
      <circle cx="33" cy="33" r="16" fill="#1044ff" opacity="0.07" />
      <rect x="19" y="37" width="7" height="12" rx="2" fill="#1044ff" opacity="0.30"
        style={{ animation: 'seo-rise3 2.4s ease-in-out infinite 0s', transformOrigin: 'center bottom', transformBox: 'fill-box' }} />
      <rect x="29" y="26" width="7" height="23" rx="2" fill="#1044ff" opacity="0.55"
        style={{ animation: 'seo-rise 2.4s ease-in-out infinite .35s', transformOrigin: 'center bottom', transformBox: 'fill-box' }} />
      <rect x="39" y="31" width="7" height="18" rx="2" fill="#1044ff" opacity="0.42"
        style={{ animation: 'seo-rise2 2.4s ease-in-out infinite .7s', transformOrigin: 'center bottom', transformBox: 'fill-box' }} />
      <line x1="49" y1="49" x2="70" y2="70" stroke="#1044ff" strokeWidth="5.5" strokeLinecap="round" opacity="0.32" />
    </svg>
  ),
  paid: (
    <svg viewBox="0 0 80 80" fill="none">
      <circle cx="40" cy="40" r="36" stroke="#1044ff" strokeWidth="1.5" opacity="0.08" />
      <circle cx="40" cy="40" r="26" stroke="#1044ff" strokeWidth="1.5" opacity="0.14" />
      <circle cx="40" cy="40" r="16" stroke="#1044ff" strokeWidth="1.5" opacity="0.22" />
      <circle cx="40" cy="40" r="7"  fill="#1044ff" opacity="0.72" style={{ animation: 'seo-pulse 1.8s ease-in-out infinite' }} />
      <circle cx="40" cy="40" r="7"  stroke="#1044ff" strokeWidth="2" opacity="0.40" style={{ animation: 'seo-ping 2s ease-out infinite' }} />
      <line x1="40" y1="2"  x2="40" y2="16" stroke="#1044ff" strokeWidth="1.5" opacity="0.16" strokeLinecap="round" />
      <line x1="40" y1="64" x2="40" y2="78" stroke="#1044ff" strokeWidth="1.5" opacity="0.16" strokeLinecap="round" />
      <line x1="2"  y1="40" x2="16" y2="40" stroke="#1044ff" strokeWidth="1.5" opacity="0.16" strokeLinecap="round" />
      <line x1="64" y1="40" x2="78" y2="40" stroke="#1044ff" strokeWidth="1.5" opacity="0.16" strokeLinecap="round" />
    </svg>
  ),
  technical: (
    <svg viewBox="0 0 80 80" fill="none">
      <rect x="30" y="4"  width="20" height="14" rx="4" fill="#1044ff" opacity="0.65" style={{ animation: 'seo-pulse 2.2s ease-in-out infinite' }} />
      <line x1="40" y1="18" x2="40" y2="32" stroke="#1044ff" strokeWidth="1.5" opacity="0.22" />
      <line x1="12" y1="32" x2="68" y2="32" stroke="#1044ff" strokeWidth="1.5" opacity="0.22" />
      <line x1="12" y1="32" x2="12" y2="40" stroke="#1044ff" strokeWidth="1.5" opacity="0.22" />
      <line x1="40" y1="32" x2="40" y2="40" stroke="#1044ff" strokeWidth="1.5" opacity="0.22" />
      <line x1="68" y1="32" x2="68" y2="40" stroke="#1044ff" strokeWidth="1.5" opacity="0.22" />
      <rect x="2"  y="40" width="20" height="12" rx="3" fill="#1044ff" opacity="0.38" style={{ animation: 'seo-node 2.4s ease-in-out infinite .2s' }} />
      <rect x="30" y="40" width="20" height="12" rx="3" fill="#1044ff" opacity="0.45" style={{ animation: 'seo-node 2.4s ease-in-out infinite .5s' }} />
      <rect x="58" y="40" width="20" height="12" rx="3" fill="#1044ff" opacity="0.38" style={{ animation: 'seo-node 2.4s ease-in-out infinite .8s' }} />
      <line x1="12" y1="52" x2="12" y2="60" stroke="#1044ff" strokeWidth="1.5" opacity="0.16" />
      <line x1="40" y1="52" x2="40" y2="60" stroke="#1044ff" strokeWidth="1.5" opacity="0.16" />
      <rect x="4"  y="60" width="16" height="8" rx="2" fill="#1044ff" opacity="0.20" />
      <rect x="32" y="60" width="16" height="8" rx="2" fill="#1044ff" opacity="0.20" />
      <rect x="52" y="60" width="16" height="8" rx="2" fill="#1044ff" opacity="0.16" />
    </svg>
  ),
  keyword: (
    <svg viewBox="0 0 80 80" fill="none">
      <rect x="4"  y="6"  width="72" height="22" rx="11" fill="#1044ff" opacity="0.10" stroke="#1044ff" strokeWidth="1.5" opacity2="0.20" />
      <circle cx="62" cy="17" r="6"  stroke="#1044ff" strokeWidth="2"   opacity="0.32" />
      <line   x1="66" y1="21" x2="72" y2="27" stroke="#1044ff" strokeWidth="2" strokeLinecap="round" opacity="0.32" />
      <rect   x="14" y="12" width="2"  height="10" rx="1" fill="#1044ff" opacity="0.50" style={{ animation: 'seo-blink 1s ease-in-out infinite' }} />
      <rect x="4"  y="38" width="30" height="12" rx="6" fill="#1044ff" opacity="0.22" style={{ animation: 'seo-float 3.2s ease-in-out infinite 0s'  }} />
      <rect x="38" y="38" width="38" height="12" rx="6" fill="#1044ff" opacity="0.32" style={{ animation: 'seo-float 3.2s ease-in-out infinite .5s' }} />
      <rect x="4"  y="56" width="46" height="12" rx="6" fill="#1044ff" opacity="0.26" style={{ animation: 'seo-float 3.2s ease-in-out infinite 1s'  }} />
      <rect x="54" y="56" width="22" height="12" rx="6" fill="#1044ff" opacity="0.18" style={{ animation: 'seo-float 3.2s ease-in-out infinite 1.5s'}} />
    </svg>
  ),
};

/* ─── service card ────────────────────────────────────────────── */
const ServiceCard = ({ svc }) => (
  <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="group h-full">
    <div className={`relative overflow-hidden rounded-[2rem] bg-white border border-gray-100 shadow-sm hover:shadow-xl hover:border-transparent transition-all duration-300 h-full ${svc.large ? 'p-8 md:p-10 min-h-[280px]' : 'p-7 md:p-8 min-h-[230px]'}`}>
      <div className="absolute inset-0 bg-gradient-to-br from-[#1044ff] to-[#0020bf] opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-[2rem]" />
      <div className="absolute bottom-4 right-4 w-20 h-20 opacity-60 group-hover:opacity-25 transition-opacity duration-300 pointer-events-none">
        {cellAnimMap[svc.animType]}
      </div>
      <div className="relative z-10 flex flex-col h-full">
        <div className="flex items-start justify-between mb-4">
          <span className="text-[10px] font-black tracking-[0.2em] uppercase px-3 py-1.5 rounded-full border text-[#1044ff] border-[#1044ff]/20 bg-[#1044ff]/8 transition-all duration-300 group-hover:bg-white/15 group-hover:border-white/25 group-hover:text-white">
            {svc.badge}
          </span>
          <ArrowUpRight className="w-5 h-5 text-gray-300 group-hover:text-white/70 transition-colors duration-300" />
        </div>
        <h3 className={`font-extrabold text-gray-900 group-hover:text-white mb-3 tracking-tight leading-tight transition-colors duration-300 ${svc.large ? 'text-xl md:text-2xl' : 'text-lg md:text-xl'}`}>{svc.title}</h3>
        <p  className={`text-gray-500 group-hover:text-white/75 leading-relaxed mb-4 flex-grow transition-colors duration-300 ${svc.large ? 'text-sm' : 'text-xs'}`}>{svc.desc}</p>
        <div className="flex flex-wrap gap-1.5">
          {svc.tags.map(tag => (
            <span key={tag} className="text-[10px] font-semibold text-gray-400 bg-white border border-gray-100 group-hover:bg-white/15 group-hover:text-white/70 group-hover:border-white/20 px-2.5 py-1 rounded-lg transition-all duration-300">{tag}</span>
          ))}
        </div>
      </div>
    </div>
  </motion.div>
);

/* ─── main component ──────────────────────────────────────────── */
const ServiceSEODigitalMarketing = () => {
  const [caseStudy,        setCaseStudy]        = useState(null);
  const [loadingCS,        setLoadingCS]        = useState(true);
  const [portfolio,        setPortfolio]        = useState([]);
  const [loadingPortfolio, setLoadingPortfolio] = useState(true);

  useEffect(() => {
    (async () => {
      try { const { data } = await supabase.from('case_studies').select('*').eq('slug', 'uk-cleaning-company').single(); setCaseStudy(data); }
      catch (e) { console.error(e); } finally { setLoadingCS(false); }
    })();
  }, []);

  useEffect(() => {
    (async () => {
      try { const { data } = await supabase.from('portfolio_projects').select('*').eq('category', 'SEO & Marketing').order('created_at', { ascending: false }).limit(3); setPortfolio(data || []); }
      catch (e) { console.error(e); } finally { setLoadingPortfolio(false); }
    })();
  }, []);

  return (
    <>
      <style>{SEO_STYLES}</style>
      <Helmet>
        <title>SEO and Digital Marketing | Maxterz</title>
        <meta name="description" content="Maxterz delivers SEO, paid advertising, technical audits, and keyword research that move your business to page one and keep it there. Get a free quote today." />
      </Helmet>

      {/* ── HERO ─────────────────────────────────────────────────── */}
      <section className="relative min-h-[82vh] flex flex-col pt-[67px] pb-20 overflow-hidden bg-white">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808015_1px,transparent_1px),linear-gradient(to_bottom,#80808015_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none" />
        <div className="absolute top-0 right-0 w-[700px] h-[700px] bg-blue-50 rounded-full blur-[120px] -translate-y-1/2 translate-x-1/3 pointer-events-none opacity-50" />
        <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-orange-50 rounded-full blur-[100px] translate-y-1/2 -translate-x-1/4 pointer-events-none opacity-60" />

        {/* SERP position floater — desktop only */}
        <div className="hidden xl:block absolute right-6 top-1/2 -translate-y-1/2 bg-white rounded-3xl shadow-2xl border border-gray-100 p-5 w-64 pointer-events-none z-10" style={{ animation: 'seo-float 4s ease-in-out infinite' }}>
          <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-3">Google — organic clicks</p>
          {[
            { pos: '#1', pct: '28.5%', w: 'w-full',  bold: true  },
            { pos: '#2', pct: '15.7%', w: 'w-[55%]', bold: false },
            { pos: '#3', pct: '11.0%', w: 'w-[38%]', bold: false },
            { pos: '#4', pct: '8.0%',  w: 'w-[28%]', bold: false },
            { pos: '#5', pct: '6.3%',  w: 'w-[22%]', bold: false },
          ].map((row, i) => (
            <div key={i} className="flex items-center gap-3 mb-2.5">
              <span className={`text-xs font-black w-6 flex-shrink-0 ${row.bold ? 'text-[#1044ff]' : 'text-gray-300'}`}>{row.pos}</span>
              <div className="flex-1 h-6 bg-gray-50 rounded-lg overflow-hidden">
                <div className={`h-full rounded-lg ${row.bold ? 'bg-gradient-to-r from-[#1044ff] to-[#3366ff]' : 'bg-gray-200'} ${row.w}`} />
              </div>
              <span className={`text-xs font-semibold w-10 text-right flex-shrink-0 ${row.bold ? 'text-[#1044ff]' : 'text-gray-400'}`}>{row.pct}</span>
            </div>
          ))}
          <div className="mt-3 pt-3 border-t border-gray-100 flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-[#1044ff] flex-shrink-0" style={{ animation: 'seo-pulse 1.6s ease-in-out infinite' }} />
            <p className="text-[11px] font-bold text-[#1044ff]">Your business should be here.</p>
          </div>
        </div>

        {/* Floating badges — left of SERP widget */}
        <div className="hidden xl:flex absolute right-[17.5rem] top-[32%] items-center gap-2 bg-white rounded-full shadow-xl border border-gray-100 px-4 py-2.5 text-sm font-bold text-gray-800 pointer-events-none z-10" style={{ animation: 'seo-float 3.5s ease-in-out infinite .5s' }}>
          <TrendingUp className="w-4 h-4 text-green-500" /> +340% organic traffic
        </div>
        <div className="hidden xl:flex absolute right-[17.5rem] top-[50%] items-center gap-2 bg-white rounded-full shadow-xl border border-gray-100 px-4 py-2.5 text-sm font-bold text-gray-800 pointer-events-none z-10" style={{ animation: 'seo-float 3.5s ease-in-out infinite 1.8s' }}>
          <Search className="w-4 h-4 text-[#1044ff]" /> Page 1 in 90 days
        </div>

        <div className="flex-1 w-full flex flex-col justify-center items-center px-4">
          <div className="container mx-auto relative z-10 text-center max-w-5xl mt-12 w-full">
            <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, ease: 'easeOut' }}>
              <span className="badge-standard-light mb-8">SEO AND DIGITAL MARKETING</span>
              <h1 className="text-5xl md:text-7xl lg:text-8xl font-black text-gray-900 mb-8 tracking-tighter leading-[1.05]">
                <span className="block">Get Found.</span>
                <span className="block">Get Clicked.</span>
                <span className="block text-[#1044ff] min-h-[1.1em]"><TypeWriter /></span>
              </h1>
              <p className="text-xl md:text-2xl text-gray-600 mb-12 max-w-3xl mx-auto font-light leading-relaxed">
                SEO strategies, paid advertising, and technical optimisation that move your business to page one and compound in value every single month.
              </p>
              <div className="flex flex-col sm:flex-row justify-center items-center gap-4 mb-12">
                <Button asChild size="lg" className="rounded-full h-14 px-8 text-lg bg-[#1044ff] hover:bg-[#0020bf] shadow-xl shadow-blue-500/20 w-full sm:w-auto transition-transform hover:scale-105">
                  <Link to="/contact">Get a Free Quote <ArrowRight className="ml-2 w-5 h-5" /></Link>
                </Button>
                <Button asChild variant="outline" size="lg" className="rounded-full h-14 px-8 text-lg border-2 w-full sm:w-auto bg-white/80">
                  <a href="https://calendly.com/maxterz-info/30min" target="_blank" rel="noopener noreferrer">
                    <Calendar className="mr-2 w-5 h-5" /> Book a Meeting
                  </a>
                </Button>
              </div>
              <div className="flex flex-wrap justify-center items-center gap-6 text-sm font-bold text-gray-800 uppercase tracking-wider">
                <span className="flex items-center gap-2"><Star className="w-4 h-4 text-[#eb7444] fill-current" /> 4.9 Stars</span>
                <span className="w-1 h-1 bg-gray-300 rounded-full" />
                <span className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-[#1044ff]" /> 7,100 Reviews</span>
                <span className="w-1 h-1 bg-gray-300 rounded-full" />
                <span className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> 11,600 Projects</span>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ── THE REALITY ───────────────────────────────────────────── */}
      <section className="relative bg-gradient-to-br from-[#1044ff] to-[#0020bf] overflow-hidden">
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none select-none">
          <span className="text-[20vw] font-black text-white/[0.04] leading-none tracking-tighter">SEO</span>
        </div>
        <div className="overflow-hidden border-b border-white/15 py-5">
          <div className="flex gap-10 whitespace-nowrap" style={{ animation: 'seo-marquee 28s linear infinite' }}>
            {[...marqueeWords, ...marqueeWords].map((w, i) => (
              <span key={i} className="text-white/30 text-[11px] font-bold uppercase tracking-[0.4em] flex-shrink-0">
                {w} <span className="text-[#e7811e] mx-2">·</span>
              </span>
            ))}
          </div>
        </div>
        <div className="container mx-auto max-w-6xl px-4 py-20 md:py-28 relative z-10">
          <p className="text-[11px] font-bold uppercase tracking-[0.35em] text-white/40 mb-8">THE REALITY</p>
          <h2 className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-black text-white leading-[0.95] tracking-tighter mb-16 md:mb-20">
            If You Are Not<br />on Page One,<br /><span className="text-[#e7811e]">You Are Not in the Game.</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-px bg-white/15 rounded-2xl overflow-hidden">
            {statsData.map((stat, i) => (
              <div key={i} className="bg-[#0020bf] p-8 md:p-10 hover:bg-white/10 transition-colors duration-300">
                <p className="text-5xl md:text-6xl font-black text-white mb-3 tracking-tighter">{stat.value}</p>
                <p className="text-white/60 text-sm leading-relaxed uppercase tracking-wider font-medium">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
        <div className="overflow-hidden border-t border-white/15 py-5">
          <div className="flex gap-10 whitespace-nowrap" style={{ animation: 'seo-marquee 22s linear infinite reverse' }}>
            {[...marqueeWords, ...marqueeWords].map((w, i) => (
              <span key={i} className="text-white/30 text-[11px] font-bold uppercase tracking-[0.4em] flex-shrink-0">
                {w} <span className="text-[#e7811e] mx-2">·</span>
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── WHAT WE DO ────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-white">
        <div className="container mx-auto max-w-6xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-14">
            <span className="badge-standard-light">WHAT WE DO</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 mt-4 mb-4 tracking-tight">
              Every Channel That Earns You Traffic.
            </h2>
            <p className="text-gray-500 text-lg max-w-2xl font-light leading-relaxed">
              Organic rankings that compound over time. Paid campaigns that convert from day one. Technical foundations that make both work better.
            </p>
          </motion.div>

          {/* 2×2 service grid */}
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {services.filter(s => s.large).map(svc => <ServiceCard key={svc.id} svc={svc} />)}
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {services.filter(s => !s.large).map(svc => <ServiceCard key={svc.id} svc={svc} />)}
            </div>
          </div>

          {/* View All Marketing Services CTA strip */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mt-4">
            <Link to="/contact" className="group flex flex-col sm:flex-row items-center justify-between gap-4 w-full rounded-[2rem] border-2 border-dashed border-[#eb7444]/30 bg-orange-50/50 hover:bg-orange-50 hover:border-[#eb7444]/60 px-8 py-6 transition-all duration-300">
              <div className="flex items-center gap-4">
                <div className="w-11 h-11 rounded-xl bg-[#eb7444]/10 border border-[#eb7444]/20 flex items-center justify-center flex-shrink-0 group-hover:bg-[#eb7444]/20 transition-colors duration-300">
                  <Globe className="w-5 h-5 text-[#eb7444]" />
                </div>
                <div>
                  <p className="font-extrabold text-gray-900 text-lg leading-tight">Other Marketing Services We Offer</p>
                  <p className="text-gray-500 text-sm mt-0.5">Explore content marketing, email campaigns, conversion rate optimisation and more.</p>
                </div>
              </div>
              <div className="flex items-center gap-2 text-[#eb7444] font-bold text-sm flex-shrink-0 group-hover:gap-3 transition-all duration-300">
                Lets market together <ChevronRight className="w-5 h-5" />
              </div>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ── HOW WE WORK ──────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-gray-50 border-y border-gray-100">
        <div className="container mx-auto max-w-5xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-16">
            <span className="badge-standard-light">OUR PROCESS</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 mt-4 mb-4 tracking-tight">
              A System Built to Rank. Not to Impress.
            </h2>
            <p className="text-gray-500 text-lg max-w-2xl font-light leading-relaxed">
              Five clear steps, zero black-box tactics. You will always know what we are doing, why we are doing it, and what it is producing.
            </p>
          </motion.div>
          <div className="relative">
            <div className="hidden md:block absolute left-[1.35rem] top-6 bottom-6 w-[2px] bg-gradient-to-b from-[#1044ff]/30 via-[#1044ff]/20 to-transparent" />
            <div className="space-y-4">
              {processSteps.map((step, i) => (
                <motion.div
                  key={step.n}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true, margin: '-60px' }}
                  transition={{ delay: i * 0.1 }}
                  className="flex gap-6 md:gap-8 items-start group"
                >
                  <div className="flex-shrink-0 w-11 h-11 rounded-full bg-white border-2 border-[#1044ff]/25 group-hover:border-[#1044ff] group-hover:bg-[#1044ff] flex items-center justify-center text-[#1044ff] group-hover:text-white font-black text-sm transition-all duration-300 shadow-sm z-10">
                    {step.n}
                  </div>
                  <div className="flex-1 bg-white rounded-[1.5rem] border border-gray-100 p-6 md:p-7 hover:shadow-lg hover:border-gray-200 transition-all duration-300 mb-1">
                    <div className="flex items-start gap-4">
                      <div className="w-9 h-9 rounded-xl bg-[#1044ff]/10 border border-[#1044ff]/15 flex items-center justify-center text-[#1044ff] flex-shrink-0 group-hover:bg-[#1044ff]/15 transition-colors duration-300">
                        {step.icon}
                      </div>
                      <div>
                        <h3 className="text-lg font-extrabold text-gray-900 mb-1.5 tracking-tight">{step.title}</h3>
                        <p className="text-gray-500 text-sm leading-relaxed">{step.desc}</p>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── CASE STUDY ──────────────────────────────────────────────
      <section className="py-24 px-4 bg-white">
        <div className="container mx-auto max-w-6xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-12">
            <span className="badge-standard-light">CASE STUDY</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 tracking-tight">Rankings That Generated Real Business.</h2>
          </motion.div>

          {loadingCS ? (
            <div className="flex justify-center py-20"><Loader2 className="w-10 h-10 animate-spin text-[#1044ff]" /></div>
          ) : !caseStudy ? (
            <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
              className="flex flex-col md:flex-row gap-8 lg:gap-12 items-center bg-gray-50 p-4 md:p-8 rounded-[2rem] border border-gray-100 hover:shadow-xl transition-all duration-500"
            >
              <div className="w-full md:w-1/2 rounded-[1.5rem] overflow-hidden aspect-[4/3] md:h-[360px] flex-shrink-0 bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center border border-blue-100">
                <Search className="w-16 h-16 text-[#1044ff]/30" />
              </div>
              <div className="w-full md:w-1/2">
                <span className="inline-block px-4 py-1.5 rounded-full bg-blue-50 text-[#1044ff] text-xs font-bold uppercase tracking-widest mb-5 border border-blue-100">UK Cleaning Company</span>
                <h3 className="text-2xl md:text-3xl font-extrabold text-gray-900 mb-4 tracking-tight leading-tight">
                  Built from Zero to Ranking on Page One Across 40+ Local Keywords
                </h3>
                <p className="text-gray-600 mb-6 leading-relaxed font-light">
                  A UK cleaning company came to us with no digital presence. We built and optimised their entire online footprint from scratch — website, on-page SEO, Google Business Profile, and a local content strategy. Within six months they were ranking on page one for their primary service keywords and receiving consistent inbound enquiries weekly.
                </p>
                <div className="grid grid-cols-3 gap-3 mb-6">
                  {[{ v: '40+', l: 'Page 1 keywords' }, { v: '6mo', l: 'To page one' }, { v: '0→∞', l: 'Inbound leads' }].map(s => (
                    <div key={s.l} className="bg-blue-50 rounded-2xl p-4 text-center border border-blue-100">
                      <p className="text-2xl font-black text-[#1044ff]">{s.v}</p>
                      <p className="text-[10px] text-gray-500 uppercase tracking-wider font-semibold mt-1">{s.l}</p>
                    </div>
                  ))}
                </div>
                <Button asChild className="rounded-full bg-[#1044ff] hover:bg-[#0020bf] text-white px-8 h-12 shadow-lg shadow-blue-500/20">
                  <Link to="/our-work">See Our Work <ArrowUpRight className="ml-2 w-4 h-4" /></Link>
                </Button>
              </div>
            </motion.div>
          ) : (
            <motion.div initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-100px' }}
              className="flex flex-col md:flex-row gap-8 lg:gap-12 items-center bg-gray-50 p-4 md:p-8 rounded-[2rem] border border-gray-100 hover:shadow-xl transition-all duration-500 group"
            >
              <div className="w-full md:w-1/2 rounded-[1.5rem] overflow-hidden bg-gray-100 aspect-[4/3] md:h-[400px] flex-shrink-0 relative">
                {caseStudy.image_url
                  ? <img src={caseStudy.image_url} alt={caseStudy.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />
                  : <div className="absolute inset-0 flex items-center justify-center"><span className="text-gray-400 text-sm">No image</span></div>
                }
              </div>
              <div className="w-full md:w-1/2 flex flex-col items-start py-4">
                {caseStudy.category_tag && (
                  <span className="inline-block px-4 py-1.5 rounded-full bg-blue-50 text-[#1044ff] text-xs font-bold uppercase tracking-widest mb-5 border border-blue-100">{caseStudy.category_tag}</span>
                )}
                <h3 className="text-2xl md:text-3xl lg:text-4xl font-extrabold text-gray-900 mb-4 tracking-tight leading-tight">{caseStudy.title}</h3>
                <p className="text-gray-600 text-base mb-6 leading-relaxed font-light">{caseStudy.description}</p>
                {caseStudy.key_result && (
                  <div className="bg-gradient-to-r from-blue-50 to-white border-l-4 border-[#1044ff] p-5 rounded-r-xl mb-6 w-full">
                    <p className="text-[#1044ff] font-bold text-xs uppercase tracking-widest mb-1.5 flex items-center gap-1.5"><CheckCircle size={14} /> Key Result</p>
                    <p className="text-gray-900 font-semibold text-sm md:text-base">{caseStudy.key_result}</p>
                  </div>
                )}
                <Button asChild className="rounded-full bg-[#1044ff] hover:bg-[#0020bf] text-white px-8 h-12 shadow-lg shadow-blue-500/20">
                  <Link to="/our-work">View Case Study <ArrowUpRight className="ml-2 w-4 h-4" /></Link>
                </Button>
              </div>
            </motion.div>
          )}
        </div>
      </section>
*/}
      {/* ── RECENT WORK ───────────────────────────────────────────── 
      <section className="py-24 px-4 bg-gradient-to-br from-[#1044ff] to-[#0020bf]">
        <div className="container mx-auto max-w-7xl">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6"
          >
            <div>
              <span className="inline-block border border-white/30 bg-white/10 rounded-full px-4 py-1.5 text-xs font-bold text-white uppercase tracking-widest mb-6">RECENT WORK</span>
              <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-white">Rankings We Have Built.</h2>
            </div>
            <Link to="/our-work" className="text-white hover:text-white/80 flex items-center gap-2 font-semibold transition-colors">
              View all work <ArrowRight size={16} />
            </Link>
          </motion.div>

          {loadingPortfolio ? (
            <div className="flex justify-center py-20"><Loader2 className="w-10 h-10 animate-spin text-white" /></div>
          ) : portfolio.length === 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {[
                { title: 'Local SEO for Cleaning Brand',    tag: 'SEO Services',      desc: '40+ page-one rankings. Consistent weekly inbound enquiries within 6 months.' },
                { title: 'Google Ads for Distribution Co.', tag: 'Paid Advertising',  desc: '£4.20 cost-per-lead on competitive B2B terms. 220% ROAS in month three.' },
                { title: 'Technical SEO Audit and Rebuild', tag: 'Technical SEO',     desc: 'Core Web Vitals moved from fail to pass. 60% crawlability improvement.' },
              ].map((item, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                  className="group bg-white rounded-[2.5rem] p-3 shadow-xl hover:shadow-2xl transition-all duration-500"
                >
                  <div className="relative overflow-hidden rounded-[2rem] aspect-[4/3] mb-4 bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center">
                    <div className="w-16 h-16 rounded-full bg-[#1044ff]/10 border border-[#1044ff]/20 flex items-center justify-center group-hover:scale-110 transition-transform duration-300">
                      <TrendingUp className="w-7 h-7 text-[#1044ff]" />
                    </div>
                  </div>
                  <div className="px-3 pb-3">
                    <p className="text-[10px] font-black uppercase tracking-widest text-[#1044ff] mb-1">{item.tag}</p>
                    <h3 className="text-xl font-bold text-gray-900 mb-1 group-hover:text-[#1044ff] transition-colors leading-tight">{item.title}</h3>
                    <p className="text-gray-500 text-sm">{item.desc}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {portfolio.map((proj, i) => (
                <motion.div key={proj.id} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                  className="group bg-white rounded-[2.5rem] p-3 shadow-xl hover:shadow-2xl transition-all duration-500"
                >
                  <Link to={`/our-work/${proj.id}`} className="block">
                    <div className="relative overflow-hidden rounded-[2rem] aspect-[4/3] mb-4 bg-gray-100">
                      <img className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 ease-out" alt={proj.title} src={proj.main_image} />
                      <div className="absolute inset-0 bg-[#1044ff]/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center backdrop-blur-sm">
                        <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center scale-50 group-hover:scale-100 transition-transform duration-300">
                          <ArrowUpRight size={32} className="text-[#1044ff]" />
                        </div>
                      </div>
                    </div>
                    <div className="px-3 pb-3">
                      <h3 className="text-2xl font-bold text-gray-900 mb-2 group-hover:text-[#1044ff] transition-colors leading-tight">{proj.title}</h3>
                      <p className="text-gray-500 font-medium text-sm line-clamp-2">{proj.short_description}</p>
                    </div>
                  </Link>
                </motion.div>
              ))}
            </div>
          )}
        </div>
      </section>
*/}      
      {/* ── FAQ ──────────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-gray-50 border-y border-gray-100">
        <div className="container mx-auto max-w-3xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16">
            <span className="badge-standard-light">QUESTIONS</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 tracking-tight">Common Questions</h2>
          </motion.div>
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqData.map((faq, idx) => (
              <AccordionItem key={idx} value={`item-${idx}`} className="bg-white px-6 rounded-2xl border border-gray-100">
                <AccordionTrigger className="text-lg font-bold hover:no-underline hover:text-[#1044ff] text-left py-6">{faq.q}</AccordionTrigger>
                <AccordionContent className="text-gray-600 pb-6 text-base leading-relaxed">{faq.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* ── BOTTOM CTA ────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-white">
        <div className="container mx-auto max-w-3xl text-center">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
            <span className="badge-standard-light mb-6">GET STARTED</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 tracking-tight mb-5">
              Your Competitors Are Already Investing in SEO.
            </h2>
            <p className="text-gray-500 text-lg font-light mb-10 max-w-xl mx-auto leading-relaxed">
              Every month without a proper SEO strategy is a month your competitors compound their lead. Tell us about your business and we will show you exactly where the opportunity is.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <Button asChild size="lg" className="rounded-full h-14 px-10 text-lg bg-[#1044ff] hover:bg-[#0020bf] shadow-xl shadow-blue-500/20 transition-transform hover:scale-105">
                <Link to="/contact">Get a Free Quote <ArrowRight className="ml-2 w-5 h-5" /></Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="rounded-full h-14 px-10 text-lg border-2">
                <a href="https://calendly.com/maxterz-info/30min" target="_blank" rel="noopener noreferrer">
                  <Calendar className="mr-2 w-5 h-5" /> Book a Meeting
                </a>
              </Button>
            </div>
          </motion.div>
        </div>
      </section>

      <CTASection />
    </>
  );
};

export default ServiceSEODigitalMarketing;
