'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import {
  ArrowRight, ArrowUpRight, Loader2, CheckCircle, Star, ShieldCheck,
  Calendar, Play, TrendingUp, MessageSquare, BarChart2, Target,
  Users, Zap, ChevronRight, Heart, Eye, PenLine, Lightbulb,
} from 'lucide-react';
import { supabase } from '@/lib/customSupabaseClient';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import WorkImageStrip from '@/components/WorkImageStrip';
import CTASection from '@/components/home/CTASection';

/* ─── keyframes ───────────────────────────────────────────────── */
const SM_STYLES = `
  @keyframes sm-blink   { 0%,100%{opacity:1} 50%{opacity:0} }
  @keyframes sm-float   { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-8px)} }
  @keyframes sm-pulse   { 0%,100%{opacity:.6;transform:scale(1)} 50%{opacity:1;transform:scale(1.12)} }
  @keyframes sm-ping    { 0%{transform:scale(1);opacity:.7} 75%,100%{transform:scale(2.4);opacity:0} }
  @keyframes sm-marquee { from{transform:translateX(0)} to{transform:translateX(-50%)} }
  @keyframes sm-bar     { 0%,100%{transform:scaleY(.42)} 50%{transform:scaleY(1)} }
  @keyframes sm-bar2    { 0%,100%{transform:scaleY(.58)} 50%{transform:scaleY(1)} }
  @keyframes sm-bar3    { 0%,100%{transform:scaleY(.33)} 50%{transform:scaleY(.82)} }
  @keyframes sm-bubble  { 0%,100%{transform:scale(1);opacity:.6} 50%{transform:scale(1.06);opacity:1} }
  @keyframes sm-node    { 0%,100%{opacity:.28} 50%{opacity:.9} }
`;

/* ─── typewriter ──────────────────────────────────────────────── */
const PHRASES = ['Revenue.', 'Leads.', 'Growth.', 'Authority.', 'Results.'];

const TypeWriter = () => {
  const [displayed,  setDisplayed]  = useState('');
  const [phraseIdx,  setPhraseIdx]  = useState(0);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const phrase = PHRASES[phraseIdx];
    let delay;
    if (!isDeleting && displayed === phrase)            delay = setTimeout(() => setIsDeleting(true), 2200);
    else if (isDeleting && displayed === '')            delay = setTimeout(() => { setIsDeleting(false); setPhraseIdx(i => (i + 1) % PHRASES.length); }, 400);
    else if (isDeleting)                                delay = setTimeout(() => setDisplayed(phrase.slice(0, displayed.length - 1)), 42);
    else                                                delay = setTimeout(() => setDisplayed(phrase.slice(0, displayed.length + 1)), 88);
    return () => clearTimeout(delay);
  }, [displayed, phraseIdx, isDeleting]);

  return (
    <span>
      {displayed}
      <span className="inline-block w-[3px] h-[0.82em] bg-[#1044ff] ml-[3px] align-middle" style={{ animation: 'sm-blink 1s ease-in-out infinite' }} />
    </span>
  );
};

/* ─── static data ─────────────────────────────────────────────── */
const marqueeWords = [
  'INSTAGRAM', 'TIKTOK', 'LINKEDIN', 'CONTENT STRATEGY', 'FACEBOOK',
  'COMMUNITY', 'ANALYTICS', 'REELS', 'ORGANIC REACH', 'PAID SOCIAL',
  'YOUTUBE', 'BRAND VOICE', 'ENGAGEMENT', 'PINTEREST',
];

const statsData = [
  { value: '4.9B', label: 'people use social media every day. They are already looking for what you offer.' },
  { value: '67%',  label: 'more leads generated by businesses that post consistently at least 3 times per week.' },
  { value: '7×',   label: 'the number of brand touchpoints needed before a buyer acts. Social keeps you there.' },
];

const platforms = [
  { name: 'Instagram', initial: 'IG', hex: '#E1306C', bg: 'bg-rose-50',   border: 'border-rose-100',   desc: 'Reels, carousels, and stories built to grow and convert.' },
  { name: 'TikTok',    initial: 'TK', hex: '#010101', bg: 'bg-gray-50',   border: 'border-gray-200',   desc: 'Short-form video scripted and edited for maximum watch time.' },
  { name: 'LinkedIn',  initial: 'Li', hex: '#0A66C2', bg: 'bg-blue-50',   border: 'border-blue-100',   desc: 'Thought leadership content that builds B2B authority and inbound leads.' },
  { name: 'Facebook',  initial: 'FB', hex: '#1877F2', bg: 'bg-sky-50',    border: 'border-sky-100',    desc: 'Community building and paid amplification that scales reach fast.' },
  { name: 'YouTube',   initial: 'YT', hex: '#FF0000', bg: 'bg-red-50',    border: 'border-red-100',    desc: 'Long-form and Shorts content that grows a channel working for you 24/7.' },
  { name: 'X',         initial: 'X',  hex: '#000000', bg: 'bg-gray-50',   border: 'border-gray-200',   desc: 'Real-time engagement, trending topics, and a sharp brand voice.' },
  { name: 'Pinterest', initial: 'Pi', hex: '#E60023', bg: 'bg-red-50',    border: 'border-red-100',    desc: 'Visual discovery content that drives consistent website traffic.' },
];

const services = [
  {
    id: 'content', badge: 'CONTENT', animType: 'content',
    badgeClass: 'text-[#1044ff] border-[#1044ff]/20 bg-[#1044ff]/8',
    title: 'Content Creation',
    desc: 'Scroll-stopping graphics, captions, and short-form video built around your brand voice. No stock photos. No generic templates. No recycled ideas.',
    tags: ['Reels', 'Carousels', 'Graphics', 'Video Scripts'],
    href: '#', isInternal: false,
  },
  {
    id: 'strategy', badge: 'STRATEGY', animType: 'strategy',
    badgeClass: 'text-[#1044ff] border-[#1044ff]/20 bg-[#1044ff]/8',
    title: 'Platform Strategy',
    desc: 'A custom content roadmap for every platform you are on. Every post has a purpose. Every caption has a role. No accidental posting, no wasted effort.',
    tags: ['Content Pillars', 'Hashtag Research', 'Timing', 'A/B Testing'],
    href: '#', isInternal: false,
  },
  {
    id: 'community', badge: 'ALWAYS ON', animType: 'community',
    badgeClass: 'text-[#1044ff] border-[#1044ff]/20 bg-[#1044ff]/8',
    title: 'Community Management',
    desc: 'Replies, DMs, and comments handled daily. The conversations that turn casual followers into customers who trust and buy from you.',
    tags: ['DM Handling', 'Comment Replies', 'Engagement', 'Daily Active'],
    href: '#', isInternal: false,
  },
  {
    id: 'analytics', badge: 'DATA', animType: 'analytics',
    badgeClass: 'text-[#1044ff] border-[#1044ff]/20 bg-[#1044ff]/8',
    title: 'Analytics and Reporting',
    desc: 'Monthly performance reports with real insights. Not just impressions. What worked, what did not, and what changes next month to improve.',
    tags: ['Monthly Reports', 'KPI Tracking', 'Competitor Data', 'Growth Trends'],
    href: '#', isInternal: false,
  },
  {
    id: 'paid', badge: 'PAID SOCIAL', animType: 'paid',
    badgeClass: 'text-[#1044ff] border-[#1044ff]/20 bg-[#1044ff]/8',
    title: 'Paid Social Ads',
    desc: 'Meta, LinkedIn, and TikTok ads that reach cold audiences and convert them into warm leads. Creative, targeting, and retargeting managed end-to-end.',
    tags: ['Meta Ads', 'LinkedIn Ads', 'TikTok Ads', 'Retargeting'],
    href: '#', isInternal: false,
  },
];

const processSteps = [
  { n: '01', icon: <BarChart2 className="w-5 h-5" />,  title: 'Social Audit',          desc: 'We analyse your existing presence, your competitors, and your audience before writing a single word of strategy or creating a single piece of content.' },
  { n: '02', icon: <Lightbulb className="w-5 h-5" />,  title: 'Strategy and Calendar', desc: 'A 30-day content calendar built around your goals, platform algorithms, and audience behaviour. Every post has a defined objective.' },
  { n: '03', icon: <PenLine className="w-5 h-5" />,    title: 'Content Creation',      desc: 'Graphics, captions, hashtags, and video scripts produced and submitted for your approval before a single post goes live. You are always in control.' },
  { n: '04', icon: <Zap className="w-5 h-5" />,        title: 'Publish and Engage',    desc: 'Posts scheduled at optimal times for each platform. Community monitored and engaged daily. No comment or DM left unanswered.' },
  { n: '05', icon: <TrendingUp className="w-5 h-5" />, title: 'Report and Optimise',   desc: 'Monthly performance report covering reach, engagement, follower growth, and lead signals. The following month\'s strategy is updated based on what worked.' },
];

const faqData = [
  { q: 'How soon will we see results?',
    a: 'Organic social takes 60 to 90 days to build consistent momentum. Engagement typically lifts in the first month, but sustainable reach and lead generation compound over 3 to 6 months. We report monthly so you see the trajectory clearly.' },
  { q: 'Do we need to provide content, or do you create everything?',
    a: 'We create everything. Copywriting, graphic design, video scripts, and editing are all included. You approve content before it is published. Nothing goes live without your sign-off.' },
  { q: 'Which platforms do you manage?',
    a: 'We manage Instagram, TikTok, LinkedIn, Facebook, YouTube, X, and Pinterest. Your package determines how many platforms are active. We recommend starting with two or three and expanding as momentum builds.' },
  { q: 'Do you run paid ads alongside organic content?',
    a: 'Yes. Paid social is included in our top-tier package and can be added to any plan. Amplifying proven organic content with paid reach is one of the fastest ways to compound results.' },
  { q: 'Will we have a dedicated point of contact?',
    a: 'Yes. Every client has a dedicated social media manager who knows your brand, handles all communication, and sends your monthly report. You are never passed around a generic support team.' },
];

/* ─── animated icons ──────────────────────────────────────────── */
const cellAnimMap = {
  content: (
    <svg viewBox="0 0 80 80" fill="none">
      <rect x="6"  y="6"  width="28" height="28" rx="5" fill="#1044ff" opacity="0.15" style={{ animation: 'sm-float 3.5s ease-in-out infinite' }} />
      <rect x="38" y="6"  width="36" height="28" rx="5" fill="#1044ff" opacity="0.25" style={{ animation: 'sm-float 3.5s ease-in-out infinite .4s' }} />
      <rect x="6"  y="38" width="20" height="36" rx="5" fill="#1044ff" opacity="0.20" style={{ animation: 'sm-float 3.5s ease-in-out infinite .8s' }} />
      <rect x="30" y="38" width="44" height="14" rx="3" fill="#1044ff" opacity="0.12" />
      <rect x="30" y="56" width="30" height="8"  rx="3" fill="#1044ff" opacity="0.09" />
      <circle cx="64" cy="64" r="10" fill="#1044ff" opacity="0.72" style={{ animation: 'sm-pulse 2s ease-in-out infinite' }} />
      <rect x="59" y="63" width="10" height="2" rx="1" fill="white" opacity="0.95" />
      <rect x="63" y="59" width="2"  height="10" rx="1" fill="white" opacity="0.95" />
    </svg>
  ),
  strategy: (
    <svg viewBox="0 0 80 80" fill="none">
      <polyline points="10,65 24,48 38,55 54,34 70,16" stroke="#1044ff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" opacity="0.28" />
      {[{ cx:10,cy:65,d:'0s' },{ cx:24,cy:48,d:'.2s' },{ cx:38,cy:55,d:'.4s' },{ cx:54,cy:34,d:'.6s' }].map((p,i) => (
        <circle key={i} cx={p.cx} cy={p.cy} r="4" fill="#1044ff" opacity="0.38" style={{ animation: `sm-node 2.4s ease-in-out infinite ${p.d}` }} />
      ))}
      <circle cx="70" cy="16" r="7" fill="#1044ff" opacity="0.80" style={{ animation: 'sm-pulse 2s ease-in-out infinite' }} />
      <polyline points="65,16 70,10 75,16" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" opacity="0.95" />
    </svg>
  ),
  community: (
    <svg viewBox="0 0 80 80" fill="none">
      <rect x="6"  y="8"  width="44" height="26" rx="9" fill="#1044ff" opacity="0.16" />
      <path d="M10 34 L6 44 L20 34" fill="#1044ff" opacity="0.16" />
      <rect x="11" y="15" width="30" height="5" rx="2.5" fill="#1044ff" opacity="0.26" />
      <rect x="11" y="24" width="18" height="5" rx="2.5" fill="#1044ff" opacity="0.20" />
      <rect x="30" y="44" width="44" height="26" rx="9" fill="#1044ff" opacity="0.32" style={{ animation: 'sm-bubble 2.5s ease-in-out infinite .7s' }} />
      <path d="M70 70 L74 80 L60 70" fill="#1044ff" opacity="0.32" style={{ animation: 'sm-bubble 2.5s ease-in-out infinite .7s' }} />
      <rect x="35" y="51" width="30" height="5" rx="2.5" fill="#1044ff" opacity="0.48" style={{ animation: 'sm-bubble 2.5s ease-in-out infinite .7s' }} />
      <rect x="35" y="60" width="18" height="5" rx="2.5" fill="#1044ff" opacity="0.38" style={{ animation: 'sm-bubble 2.5s ease-in-out infinite .7s' }} />
    </svg>
  ),
  analytics: (
    <svg viewBox="0 0 80 80" fill="none">
      <rect x="8"  y="18" width="13" height="54" rx="3" fill="#1044ff" opacity="0.42"
        style={{ animation: 'sm-bar 2.4s ease-in-out infinite', transformOrigin: 'center bottom', transformBox: 'fill-box' }} />
      <rect x="27" y="8"  width="13" height="64" rx="3" fill="#1044ff" opacity="0.62"
        style={{ animation: 'sm-bar2 2.4s ease-in-out infinite .3s', transformOrigin: 'center bottom', transformBox: 'fill-box' }} />
      <rect x="46" y="26" width="13" height="46" rx="3" fill="#1044ff" opacity="0.38"
        style={{ animation: 'sm-bar3 2.4s ease-in-out infinite .6s', transformOrigin: 'center bottom', transformBox: 'fill-box' }} />
      <rect x="65" y="14" width="13" height="58" rx="3" fill="#1044ff" opacity="0.72"
        style={{ animation: 'sm-bar2 2.4s ease-in-out infinite .9s', transformOrigin: 'center bottom', transformBox: 'fill-box' }} />
    </svg>
  ),
  paid: (
    <svg viewBox="0 0 80 80" fill="none">
      <circle cx="40" cy="40" r="30" stroke="#1044ff" strokeWidth="1.5" opacity="0.10" />
      <circle cx="40" cy="40" r="22" stroke="#1044ff" strokeWidth="1.5" opacity="0.18" />
      <circle cx="40" cy="40" r="13" stroke="#1044ff" strokeWidth="1.5" opacity="0.30" />
      <circle cx="40" cy="40" r="5"  fill="#1044ff"   opacity="0.78" style={{ animation: 'sm-pulse 1.8s ease-in-out infinite' }} />
      <circle cx="40" cy="40" r="5"  stroke="#1044ff" strokeWidth="2" opacity="0.50" style={{ animation: 'sm-ping 2s ease-out infinite' }} />
    </svg>
  ),
};

/* ─── service card ────────────────────────────────────────────── */
const ServiceCard = ({ svc, compact = false }) => (
  <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="group h-full">
    <div className={`relative overflow-hidden rounded-[2rem] bg-white border border-gray-100 shadow-sm hover:shadow-xl hover:border-transparent transition-all duration-300 h-full ${compact ? 'p-6 min-h-[200px]' : 'p-8 min-h-[280px]'}`}>
      <div className="absolute inset-0 bg-gradient-to-br from-[#1044ff] to-[#0020bf] opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-[2rem]" />
      <div className="absolute bottom-4 right-4 w-20 h-20 opacity-60 group-hover:opacity-30 transition-opacity duration-300 pointer-events-none text-[#1044ff]">
        {cellAnimMap[svc.animType]}
      </div>
      <div className="relative z-10 flex flex-col h-full">
        <div className="flex items-start justify-between mb-4">
          <span className={`text-[10px] font-black tracking-[0.2em] uppercase px-3 py-1.5 rounded-full border transition-all duration-300 ${svc.badgeClass} group-hover:bg-white/15 group-hover:border-white/25 group-hover:text-white`}>
            {svc.badge}
          </span>
          <ArrowUpRight className="w-5 h-5 text-gray-300 group-hover:text-white/70 transition-colors duration-300" />
        </div>
        <h3 className={`font-extrabold text-gray-900 group-hover:text-white mb-2 tracking-tight leading-tight transition-colors duration-300 ${compact ? 'text-lg' : 'text-xl md:text-2xl'}`}>{svc.title}</h3>
        <p  className={`text-gray-500 group-hover:text-white/75 leading-relaxed mb-4 flex-grow transition-colors duration-300 ${compact ? 'text-xs' : 'text-sm'}`}>{svc.desc}</p>
        <div className="flex flex-wrap gap-1.5">
          {svc.tags.map(tag => (
            <span key={tag} className="text-[10px] font-semibold text-gray-400 bg-white border border-gray-100 group-hover:bg-white/15 group-hover:text-white/70 group-hover:border-white/20 px-2.5 py-1 rounded-lg transition-all duration-300">{tag}</span>
          ))}
        </div>
      </div>
    </div>
  </motion.div>
);

/* ─── main component ──────────────────────────────────────────── */
const ServiceSocialMediaManagement = () => {
  const [packages,         setPackages]         = useState([]);
  const [loadingPackages,  setLoadingPackages]  = useState(true);
  const [caseStudy,        setCaseStudy]        = useState(null);
  const [loadingCS,        setLoadingCS]        = useState(true);
  const [portfolio,        setPortfolio]        = useState([]);
  const [loadingPortfolio, setLoadingPortfolio] = useState(true);

  useEffect(() => {
    (async () => {
      try { const { data } = await supabase.from('SocialMediaPackages').select('*').order('display_order', { ascending: true }); setPackages(data || []); }
      catch (e) { console.error(e); } finally { setLoadingPackages(false); }
    })();
  }, []);

  useEffect(() => {
    (async () => {
      try { const { data } = await supabase.from('case_studies').select('*').eq('slug', 'uk-cleaning-company').single(); setCaseStudy(data); }
      catch (e) { console.error(e); } finally { setLoadingCS(false); }
    })();
  }, []);

  useEffect(() => {
    (async () => {
      try { const { data } = await supabase.from('portfolio_projects').select('*').eq('category', 'Social Media').order('created_at', { ascending: false }).limit(3); setPortfolio(data || []); }
      catch (e) { console.error(e); } finally { setLoadingPortfolio(false); }
    })();
  }, []);

  return (
    <>
      <style>{SM_STYLES}</style>

      {/* ── HERO ─────────────────────────────────────────────────── */}
      <section className="relative min-h-[80vh] flex flex-col pt-[67px] pb-8 overflow-hidden bg-white">
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808015_1px,transparent_1px),linear-gradient(to_bottom,#80808015_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none" />
        <div className="absolute top-0 right-0 w-[700px] h-[700px] bg-blue-50 rounded-full blur-[120px] -translate-y-1/2 translate-x-1/3 pointer-events-none opacity-50" />
        <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-orange-50 rounded-full blur-[100px] translate-y-1/2 -translate-x-1/4 pointer-events-none opacity-60" />

        {/* Floating engagement badges — desktop decoration */}
        <div className="hidden xl:flex absolute right-20 top-[30%] items-center gap-2 bg-white rounded-full shadow-xl border border-gray-100 px-4 py-2.5 text-sm font-bold text-gray-800 pointer-events-none z-10" style={{ animation: 'sm-float 3.5s ease-in-out infinite' }}>
          <Heart className="w-4 h-4 text-rose-500 fill-rose-500" /> +2,841 this week
        </div>
        <div className="hidden xl:flex absolute right-8 top-[48%] items-center gap-2 bg-white rounded-full shadow-xl border border-gray-100 px-4 py-2.5 text-sm font-bold text-gray-800 pointer-events-none z-10" style={{ animation: 'sm-float 3.5s ease-in-out infinite 1.2s' }}>
          <Users className="w-4 h-4 text-[#1044ff]" /> +1.4K followers
        </div>
        <div className="hidden xl:flex absolute right-24 top-[62%] items-center gap-2 bg-white rounded-full shadow-xl border border-gray-100 px-4 py-2.5 text-sm font-bold text-gray-800 pointer-events-none z-10" style={{ animation: 'sm-float 3.5s ease-in-out infinite 2.4s' }}>
          <Eye className="w-4 h-4 text-green-500" /> 94.2K reach
        </div>

        <div className="flex-1 w-full flex flex-col justify-center items-center px-4">
          <div className="container mx-auto relative z-10 text-center max-w-5xl mt-12 w-full">
            <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, ease: 'easeOut' }}>
              <span className="badge-standard-light mb-8">SOCIAL MEDIA MANAGEMENT</span>
              <h1 className="text-5xl md:text-7xl lg:text-8xl font-black text-gray-900 mb-8 tracking-tighter leading-[1.05]">
                <span className="block">Your Social Media.</span>
                <span className="block">Built for</span>
                <span className="block text-[#1044ff] min-h-[1.1em]"><TypeWriter /></span>
              </h1>
              <p className="text-xl md:text-2xl text-gray-600 mb-12 max-w-3xl mx-auto font-light leading-relaxed">
                We plan, create, schedule, and manage your entire social presence. You focus on the business. We make sure the world knows about it.
              </p>
              <div className="flex flex-col sm:flex-row justify-center items-center gap-4 mb-12">
                <Button asChild size="lg" className="rounded-full h-14 px-8 text-lg bg-[#1044ff] hover:bg-[#0020bf] shadow-xl shadow-blue-500/20 w-full sm:w-auto transition-transform hover:scale-105">
                  <Link href="/contact">Start Growing Today <ArrowRight className="ml-2 w-5 h-5" /></Link>
                </Button>
                <Button asChild variant="outline" size="lg" className="rounded-full h-14 px-8 text-lg border-2 w-full sm:w-auto bg-white/80">
                  <a href="https://calendly.com/maxterz-info/30min" target="_blank" rel="noopener noreferrer">
                    <Calendar className="mr-2 w-5 h-5" /> Book a Free Call
                  </a>
                </Button>
              </div>
              <div className="flex flex-wrap justify-center items-center gap-6 text-sm font-bold text-gray-800 uppercase tracking-wider">
                <span className="flex items-center gap-2"><Star className="w-4 h-4 text-[#eb7444] fill-current" /> 4.9 Stars</span>
                <span className="w-1 h-1 bg-gray-300 rounded-full" />
                <span className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-[#1044ff]" /> 7,100 Reviews</span>
                <span className="w-1 h-1 bg-gray-300 rounded-full" />
                <span className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> 11,600 Projects</span>
              </div>
            </motion.div>
          </div>
        </div>
        <WorkImageStrip table="SocialMediaSlideImages" label="Social Media Work" fadeColor="#ffffff" />
      </section>

      {/* ── THE TRUTH ────────────────────────────────────────────── */}
      <section className="relative bg-gradient-to-br from-[#1044ff] to-[#0020bf] overflow-hidden">
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none select-none">
          <span className="text-[20vw] font-black text-white/[0.04] leading-none tracking-tighter">SOCIAL</span>
        </div>
        <div className="overflow-hidden border-b border-white/15 py-5">
          <div className="flex gap-10 whitespace-nowrap" style={{ animation: 'sm-marquee 30s linear infinite' }}>
            {[...marqueeWords, ...marqueeWords].map((w, i) => (
              <span key={i} className="text-white/30 text-[11px] font-bold uppercase tracking-[0.4em] flex-shrink-0">
                {w} <span className="text-[#e7811e] mx-2">·</span>
              </span>
            ))}
          </div>
        </div>
        <div className="container mx-auto max-w-6xl px-4 py-20 md:py-28 relative z-10">
          <p className="text-[11px] font-bold uppercase tracking-[0.35em] text-white/40 mb-8">THE TRUTH</p>
          <h2 className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-black text-white leading-[0.95] tracking-tighter mb-16 md:mb-20">
            Social Is Not<br />About Followers.<br /><span className="text-[#e7811e]">It Is About Revenue.</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-px bg-white/15 rounded-2xl overflow-hidden">
            {statsData.map((stat, i) => (
              <div key={i} className="bg-[#0020bf] p-8 md:p-10 hover:bg-white/10 transition-colors duration-300">
                <p className="text-5xl md:text-6xl font-black text-white mb-3 tracking-tighter">{stat.value}</p>
                <p className="text-white/60 text-sm leading-relaxed uppercase tracking-wider font-medium">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
        <div className="overflow-hidden border-t border-white/15 py-5">
          <div className="flex gap-10 whitespace-nowrap" style={{ animation: 'sm-marquee 22s linear infinite reverse' }}>
            {[...marqueeWords, ...marqueeWords].map((w, i) => (
              <span key={i} className="text-white/30 text-[11px] font-bold uppercase tracking-[0.4em] flex-shrink-0">
                {w} <span className="text-[#e7811e] mx-2">·</span>
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── WHAT WE DO ────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-white">
        <div className="container mx-auto max-w-6xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-14">
            <span className="badge-standard-light">WHAT WE DO</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 mt-4 mb-4 tracking-tight">
              Content That Works. Not Content That Exists.
            </h2>
            <p className="text-gray-500 text-lg max-w-2xl font-light leading-relaxed">
              Most agencies post. We strategise, create, engage, and measure. Every piece of content has a job to do.
            </p>
          </motion.div>

          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {services.slice(0, 2).map(svc => <ServiceCard key={svc.id} svc={svc} compact={false} />)}
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {services.slice(2).map(svc => <ServiceCard key={svc.id} svc={svc} compact={true} />)}
            </div>
          </div>
        </div>
      </section>

      {/* ── PLATFORMS ────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-gray-50 border-y border-gray-100">
        <div className="container mx-auto max-w-6xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-14">
            <span className="badge-standard-light">PLATFORMS</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 tracking-tight mt-4 mb-4">
              7 Platforms. One Team. Zero Gaps.
            </h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto font-light">
              Wherever your audience is, we are already there — with content built for that platform, not repurposed from somewhere else.
            </p>
          </motion.div>

          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-7 gap-3">
            {platforms.map((p, i) => (
              <motion.div
                key={p.name}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.07 }}
                className="group relative"
              >
                <div className={`rounded-[1.5rem] ${p.bg} border ${p.border} p-5 flex flex-col items-center gap-3 hover:shadow-lg transition-all duration-300 cursor-default hover:-translate-y-1`}>
                  <div className="w-11 h-11 rounded-xl flex items-center justify-center font-black text-sm text-white shadow-sm"
                    style={{ backgroundColor: p.hex }}>
                    {p.initial}
                  </div>
                  <p className="text-xs font-bold text-gray-800 text-center">{p.name}</p>
                </div>
                {/* Hover tooltip */}
                <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-3 w-52 bg-gray-900 text-white text-xs leading-relaxed rounded-xl px-4 py-3 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 z-20 text-center shadow-xl">
                  {p.desc}
                  <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-gray-900" />
                </div>
              </motion.div>
            ))}
          </div>
          <p className="text-center text-gray-400 text-sm mt-8">Hover each platform to see what we do there.</p>
        </div>
      </section>

      {/* ── PROCESS ──────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-white">
        <div className="container mx-auto max-w-5xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-16">
            <span className="badge-standard-light">HOW WE WORK</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 mt-4 mb-4 tracking-tight">
              Structured. Strategic. Measurable.
            </h2>
            <p className="text-gray-500 text-lg max-w-2xl font-light leading-relaxed">
              Every account we manage follows the same five-step system — built for consistency, optimised for growth.
            </p>
          </motion.div>

          {/* Timeline */}
          <div className="relative">
            <div className="hidden md:block absolute left-[1.35rem] top-6 bottom-6 w-[2px] bg-gradient-to-b from-[#1044ff]/30 via-[#1044ff]/20 to-transparent" />
            <div className="space-y-4">
              {processSteps.map((step, i) => (
                <motion.div
                  key={step.n}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true, margin: '-60px' }}
                  transition={{ delay: i * 0.1 }}
                  className="flex gap-6 md:gap-8 items-start group"
                >
                  {/* Timeline node */}
                  <div className="flex-shrink-0 w-11 h-11 rounded-full bg-white border-2 border-[#1044ff]/25 group-hover:border-[#1044ff] group-hover:bg-[#1044ff] flex items-center justify-center text-[#1044ff] group-hover:text-white font-black text-sm transition-all duration-300 shadow-sm z-10">
                    {step.n}
                  </div>
                  {/* Card */}
                  <div className="flex-1 bg-gray-50 rounded-[1.5rem] border border-gray-100 p-6 md:p-7 hover:bg-white hover:shadow-lg hover:border-gray-200 transition-all duration-300 mb-1">
                    <div className="flex items-start gap-4">
                      <div className="w-9 h-9 rounded-xl bg-[#1044ff]/10 border border-[#1044ff]/15 flex items-center justify-center text-[#1044ff] flex-shrink-0 group-hover:bg-[#1044ff]/15 transition-colors duration-300">
                        {step.icon}
                      </div>
                      <div>
                        <h3 className="text-lg font-extrabold text-gray-900 mb-1.5 tracking-tight">{step.title}</h3>
                        <p className="text-gray-500 text-sm leading-relaxed">{step.desc}</p>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── CASE STUDY ──────────────────────────────────────────────
      <section className="py-24 px-4 bg-gray-50 border-y border-gray-100">
        <div className="container mx-auto max-w-6xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-12">
            <span className="badge-standard-light">CASE STUDY</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 tracking-tight">It Works. Here Is the Proof.</h2>
          </motion.div>

          {loadingCS ? (
            <div className="flex justify-center py-20"><Loader2 className="w-10 h-10 animate-spin text-[#1044ff]" /></div>
          ) : !caseStudy ? (
            <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
              className="flex flex-col md:flex-row gap-8 lg:gap-12 items-center bg-white p-4 md:p-8 rounded-[2rem] border border-gray-100 hover:shadow-xl transition-all duration-500"
            >
              <div className="w-full md:w-1/2 rounded-[1.5rem] overflow-hidden aspect-[4/3] md:h-[360px] flex-shrink-0 bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center border border-blue-100">
                <Play className="w-12 h-12 text-[#1044ff]/40" />
              </div>
              <div className="w-full md:w-1/2">
                <span className="inline-block px-4 py-1.5 rounded-full bg-blue-50 text-[#1044ff] text-xs font-bold uppercase tracking-widest mb-5 border border-blue-100">UK Cleaning Brand</span>
                <h3 className="text-2xl md:text-3xl font-extrabold text-gray-900 mb-4 tracking-tight leading-tight">
                  From Zero Presence to 12,000 Followers and a Consistent Lead Stream in 6 Months
                </h3>
                <p className="text-gray-600 mb-6 leading-relaxed font-light">
                  A UK cleaning company came to us with no social presence and no content strategy. Six months later they had 12K followers across Instagram and TikTok, a content system running on autopilot, and inbound enquiries every week from social alone.
                </p>
                <div className="grid grid-cols-3 gap-3 mb-6">
                  {[{ v: '12K', l: 'Followers gained' }, { v: '340%', l: 'Engagement lift' }, { v: '6mo', l: 'To full momentum' }].map(s => (
                    <div key={s.l} className="bg-blue-50 rounded-2xl p-4 text-center border border-blue-100">
                      <p className="text-2xl font-black text-[#1044ff]">{s.v}</p>
                      <p className="text-[10px] text-gray-500 uppercase tracking-wider font-semibold mt-1">{s.l}</p>
                    </div>
                  ))}
                </div>
                <Button asChild className="rounded-full bg-[#1044ff] hover:bg-[#0020bf] text-white px-8 h-12 shadow-lg shadow-blue-500/20">
                  <Link to="/our-work">See Our Work <ArrowUpRight className="ml-2 w-4 h-4" /></Link>
                </Button>
              </div>
            </motion.div>
          ) : (
            <motion.div initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-100px' }}
              className="flex flex-col md:flex-row gap-8 lg:gap-12 items-center bg-white p-4 md:p-8 rounded-[2rem] border border-gray-100 hover:shadow-xl transition-all duration-500 group"
            >
              <div className="w-full md:w-1/2 rounded-[1.5rem] overflow-hidden bg-gray-100 aspect-[4/3] md:h-[400px] flex-shrink-0 relative">
                {caseStudy.image_url
                  ? <img src={caseStudy.image_url} alt={caseStudy.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />
                  : <div className="absolute inset-0 flex items-center justify-center"><span className="text-gray-400 text-sm">No image</span></div>
                }
              </div>
              <div className="w-full md:w-1/2 flex flex-col items-start py-4">
                {caseStudy.category_tag && (
                  <span className="inline-block px-4 py-1.5 rounded-full bg-blue-50 text-[#1044ff] text-xs font-bold uppercase tracking-widest mb-5 border border-blue-100">{caseStudy.category_tag}</span>
                )}
                <h3 className="text-2xl md:text-3xl lg:text-4xl font-extrabold text-gray-900 mb-4 tracking-tight leading-tight">{caseStudy.title}</h3>
                <p className="text-gray-600 text-base mb-6 leading-relaxed font-light">{caseStudy.description}</p>
                {caseStudy.key_result && (
                  <div className="bg-gradient-to-r from-blue-50 to-white border-l-4 border-[#1044ff] p-5 rounded-r-xl mb-6 w-full">
                    <p className="text-[#1044ff] font-bold text-xs uppercase tracking-widest mb-1.5 flex items-center gap-1.5"><CheckCircle size={14} /> Key Result</p>
                    <p className="text-gray-900 font-semibold text-sm md:text-base">{caseStudy.key_result}</p>
                  </div>
                )}
                <Button asChild className="rounded-full bg-[#1044ff] hover:bg-[#0020bf] text-white px-8 h-12 shadow-lg shadow-blue-500/20">
                  <Link to="/our-work">View Case Study <ArrowUpRight className="ml-2 w-4 h-4" /></Link>
                </Button>
              </div>
            </motion.div>
          )}
        </div>
      </section>
*/}

      {/* ── RECENT WORK ───────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-gradient-to-br from-[#1044ff] to-[#0020bf]">
        <div className="container mx-auto max-w-7xl">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6"
          >
            <div>
              <span className="inline-block border border-white/30 bg-white/10 rounded-full px-4 py-1.5 text-xs font-bold text-white uppercase tracking-widest mb-6">RECENT WORK</span>
              <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-white">Social That Performs.</h2>
            </div>
            <Link href="/our-work" className="text-white hover:text-white/80 flex items-center gap-2 font-semibold transition-colors">
              View all work <ArrowRight size={16} />
            </Link>
          </motion.div>

          {loadingPortfolio ? (
            <div className="flex justify-center py-20"><Loader2 className="w-10 h-10 animate-spin text-white" /></div>
          ) : portfolio.length === 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {[
                { title: 'SaaS Brand Social Launch', tag: 'Instagram + LinkedIn', desc: '0 to 8K followers in 90 days with an organic-only strategy.' },
                { title: 'E-Commerce TikTok Growth', tag: 'TikTok + Reels',       desc: '3.2M views on a single product video. 400% revenue spike that week.' },
                { title: 'B2B LinkedIn Authority',   tag: 'LinkedIn',              desc: 'Monthly inbound leads doubled within 4 months of consistent content.' },
              ].map((item, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                  className="group bg-white rounded-[2.5rem] p-3 shadow-xl hover:shadow-2xl transition-all duration-500"
                >
                  <div className="relative overflow-hidden rounded-[2rem] aspect-[4/3] mb-4 bg-gradient-to-br from-blue-50 to-blue-100 flex items-center justify-center">
                    <div className="w-16 h-16 rounded-full bg-[#1044ff]/10 border border-[#1044ff]/20 flex items-center justify-center group-hover:scale-110 transition-transform duration-300">
                      <TrendingUp className="w-7 h-7 text-[#1044ff]" />
                    </div>
                  </div>
                  <div className="px-3 pb-3">
                    <p className="text-[10px] font-black uppercase tracking-widest text-[#1044ff] mb-1">{item.tag}</p>
                    <h3 className="text-xl font-bold text-gray-900 mb-1 group-hover:text-[#1044ff] transition-colors leading-tight">{item.title}</h3>
                    <p className="text-gray-500 text-sm">{item.desc}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {portfolio.map((proj, i) => (
                <motion.div key={proj.id} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}
                  className="group bg-white rounded-[2.5rem] p-3 shadow-xl hover:shadow-2xl transition-all duration-500"
                >
                  <Link href={`/our-work/${proj.id}`} className="block">
                    <div className="relative overflow-hidden rounded-[2rem] aspect-[4/3] mb-4 bg-gray-100">
                      <img className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 ease-out" alt={proj.title} src={proj.main_image} />
                      <div className="absolute inset-0 bg-[#1044ff]/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center backdrop-blur-sm">
                        <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center scale-50 group-hover:scale-100 transition-transform duration-300">
                          <ArrowUpRight size={32} className="text-[#1044ff]" />
                        </div>
                      </div>
                    </div>
                    <div className="px-3 pb-3">
                      <h3 className="text-2xl font-bold text-gray-900 mb-2 group-hover:text-[#1044ff] transition-colors leading-tight">{proj.title}</h3>
                      <p className="text-gray-500 font-medium text-sm line-clamp-2">{proj.short_description}</p>
                    </div>
                  </Link>
                </motion.div>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* ── PACKAGES ─────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-white">
        <div className="container mx-auto max-w-6xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16">
            <span className="badge-standard-light">PRICING</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 mb-6 tracking-tight">
              Pick Your Plan. <span className="text-[#1044ff]">We Handle the Rest.</span>
            </h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto font-light">Flat-rate monthly management. No hourly billing. No hidden costs. Cancel anytime.</p>
          </motion.div>

          {loadingPackages ? (
            <div className="flex justify-center py-20"><Loader2 className="w-10 h-10 animate-spin text-[#1044ff]" /></div>
          ) : packages.length === 0 ? (
            <div className="text-center text-gray-400 py-10">Packages coming soon.</div>
          ) : (
            <div className="grid md:grid-cols-3 gap-6 items-stretch">
              {packages.map((pkg, i) => {
                const isFeatured = pkg.is_featured;
                const features   = typeof pkg.features === 'string' ? JSON.parse(pkg.features) : (pkg.features || []);
                return (
                  <motion.div key={pkg.id} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.15 }}
                    className={`relative rounded-[2rem] p-8 md:p-10 flex flex-col gap-5 border transition-all duration-300 ${isFeatured ? 'bg-gradient-to-br from-[#1044ff] to-[#0020bf] border-transparent shadow-2xl shadow-blue-500/25 scale-[1.02]' : 'bg-white border-gray-100 shadow-sm hover:shadow-xl hover:-translate-y-1'}`}
                  >
                    {isFeatured && (
                      <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 text-[11px] font-black uppercase tracking-widest px-4 py-1.5 rounded-full bg-[#e7811e] text-white shadow">Most Popular</span>
                    )}
                    <span className={`text-[10px] font-bold uppercase tracking-[0.25em] ${isFeatured ? 'text-white/50' : 'text-gray-400'}`}>Monthly Management</span>
                    <h3 className={`text-2xl font-black tracking-tight ${isFeatured ? 'text-white' : 'text-gray-900'}`}>{pkg.name}</h3>
                    {pkg.description && <p className={`text-sm leading-relaxed ${isFeatured ? 'text-white/75' : 'text-gray-500'}`}>{pkg.description}</p>}
                    <div className="flex items-end gap-1">
                      <span className={`text-5xl font-black tracking-tighter ${isFeatured ? 'text-white' : 'text-gray-900'}`}>£{Number(pkg.price).toLocaleString()}</span>
                      <span className={`text-lg font-semibold mb-1.5 ${isFeatured ? 'text-white/60' : 'text-gray-500'}`}>/month</span>
                    </div>
                    <div className={`h-px w-full ${isFeatured ? 'bg-white/15' : 'bg-gray-100'}`} />
                    <ul className="flex flex-col gap-3 flex-grow">
                      {features.map((feat, fi) => (
                        <li key={fi} className="flex items-start gap-3">
                          <CheckCircle size={16} className={`flex-shrink-0 mt-0.5 ${isFeatured ? 'text-white/60' : 'text-[#1044ff]'}`} />
                          <span className={`text-sm leading-relaxed ${isFeatured ? 'text-white/80' : 'text-gray-600'}`}>{feat}</span>
                        </li>
                      ))}
                    </ul>
                    <Button asChild size="lg" className={`rounded-full h-12 text-sm font-bold mt-auto transition-transform hover:scale-105 ${isFeatured ? 'bg-white text-[#1044ff] hover:bg-gray-100 shadow-lg' : 'bg-[#1044ff] text-white hover:bg-[#0020bf]'}`}>
                      <Link href="/contact">Get Started <ArrowRight className="ml-2 w-4 h-4" /></Link>
                    </Button>
                  </motion.div>
                );
              })}
            </div>
          )}
          <p className="text-center text-gray-400 text-sm mt-10">
            Need a bespoke plan?{' '}
            <a href="https://calendly.com/maxterz-info/30min" target="_blank" rel="noopener noreferrer" className="text-[#1044ff] font-semibold hover:underline">
              Book a free call and we will scope it together.
            </a>
          </p>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────────── */}
      <section className="py-24 px-4 bg-gray-50 border-y border-gray-100">
        <div className="container mx-auto max-w-3xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16">
            <span className="badge-standard-light">QUESTIONS</span>
            <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 tracking-tight">Common Questions</h2>
          </motion.div>
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqData.map((faq, idx) => (
              <AccordionItem key={idx} value={`item-${idx}`} className="bg-white px-6 rounded-2xl border border-gray-100">
                <AccordionTrigger className="text-lg font-bold hover:no-underline hover:text-[#1044ff] text-left py-6">{faq.q}</AccordionTrigger>
                <AccordionContent className="text-gray-600 pb-6 text-base leading-relaxed">{faq.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      <CTASection />
    </>
  );
};

export default ServiceSocialMediaManagement;
